# Generated by Django 6.1 on 2026-08-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewquestion',
            old_name='question_number',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='ai_feedback',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='ai_score',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='user_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
