# Generated by Django 6.1 on 2026-08-19 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_rename_question_number_interviewquestion_order_and_more'),
        ('resumes', '0004_resumeanalysis_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='resumes.resume'),
        ),
    ]
