# Generated by Django 6.1 on 2026-08-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_interview_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='answer_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='answer_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
