# Generated by Django 6.0.2 on 2026-08-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interviewquestion_answer_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('resume', 'Resume Based'), ('topic', 'Topic Based'), ('hr', 'HR Interview')], default='resume', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('introduction', 'Self Introduction'), ('technical', 'Technical'), ('hr', 'HR')], default='technical', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
