# Generated by Django 5.2.17 on 2026-08-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='target_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
